url: http://edwingrafik.pl/
baseurl: /edwingrafik.github.io/
# Site settings
author: Edwin Gawron
title: edwingrafik | projekty graficzne częstochowa | identyfikacja wizualna
email: edwingawron@gmail.com
description: "Projekt logo, identyfikacja wizualna, wyróżniające się wizytówki dla pracowników. Projekty graficzne, których potrzebuje Twoja firma. Edwin Grafik Częstochowa"
keywords: logo | grafik częstochowa | edwingrafik | projekty do druku | wizytowki firmowe | identyfikacja wizualna | branding | design
# Team names, titles and social links
people:
- name: Edwin Gawron
  pic: 1
  position: Specjalista w dziedzinie dobrego designu
  social:
    - title: twitter
      url: https://twitter.com/edwingrafik
    - title: facebook
      url: https://www.facebook.com/edwingrafik/
    - title: linkedin
      url: https://www.linkedin.com/in/edwin-gawron-6b395998?trk=nav_responsive_tab_profile
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/edwingrafik
  - title: facebook
    url: https://www.facebook.com/edwingrafik/
  - title: instagram
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: linkedin
    url: http://bitbucket.org/jekyll
  - title: google-plus
    url: http://github.com/jekyll
# Build settings
markdown: kramdown
permalink: pretty
gems:
  - jekyll-sitemap
# Google services
google_analytics: UA-80178621-1

